openapi: 3.0.3
info:
  title: Pillow Service
  description: Pillow Service API for managing products
  contact:
    email: elizaveta_olenchenko@epam.com
  version: 1.0.0
servers:
  - url: https://ysck7ne6c3.execute-api.eu-west-1.amazonaws.com/dev/
tags:
  - name: products
    description: APIs for managing products
paths:
  /products:
    get:
      tags:
        - products
      summary: Get all pillows
      operationId: getProductsList
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
              examples:
                example1:
                  value:
                    - id: "1",
                      title: "Pillow 1",
                      description: "Pillow 1 description",
                      matherials: "Coton",
                      filler: "Polyester Fiberfill",
                      height: 50, 
                      width: 70,
                      price: 57
                    - id: "2",
                      title: "pillow 2",
                      description: "Pillow 2 description",
                      matherials: "Synthetic fibers",
                      filler: "Polyester Fiberfill",
                      height: 50, 
                      width: 50,
                      price: 50
        '500':
          description: Error during getting pillows
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example1:
                  value:
                    message: 'An error occurred while getting the product.'
  /products/{productId}:
    get:
      tags:
        - products
      summary: Get pillow by product ID
      operationId: getProductsById
      parameters:
        - name: productId
          in: path
          description: 'The product ID that needs to be fetched. Use "1" for testing.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                example1:
                  value:
                    id: "1",
                    title: "Pillow 1",
                    description: "Pillow 1 description",
                    matherials: "Coton",
                    filler: "Polyester Fiberfill",
                    height: 50, 
                    width: 70,
                    price: 57
        '500':
          description: Error during getting product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example1:
                  value:
                    message: 'An error occurred while getting the product.'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                example1:
                  value:
                    message: 'The product with ID 1 was not found.'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A message that describes the error that occurred.
      example:
        message: 'An error occurred while getting pillows.'
    Product:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the pillow.
          example: '1'
        title:
          type: string
          description: The title of the pillow.
          example: 'Pillow 1'
        description:
          type: string
          description: The description of the pillow.
          example: 'Pillow 1 description'  
        matherials:
          type: string
          description: The top matherials of the pillow.
          example: "Coton"
        filler:
          type: string
          description: The inside filler of the pillow.
          example: "Polyester Fiberfill"
        height:
          type: number
          format: float
          description: The height of the product.
          example: 50
        width:
          type: number
          format: float
          description: The width of the product.
          example: 70
        price:
          type: number
          format: float
          description: The price of the product.
          example: 300
        count:
          type: number
          format: integer
          description: The count of the product.
          example: 10
      required:
        - id,
        - title,
        - matherials,
        - filler,
        - height, 
        - width,
        - price
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'
      example:
        - title: 'Product A'
          id: '1'
          description:
      uniqueItems: true
      additionalProperties: false
      description: List of products
 18,400  
product-service/pa